wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709769853.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.13
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
