name: mlflow-b71ce8844054e0c802e265ec9d1ee4558a5639cf
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alembic=1.13.1=pyhd8ed1ab_1
  - alsa-lib=1.2.11=hd590300_1
  - attr=2.5.1=h166bdaf_1
  - aws-c-auth=0.7.16=h79b3bcb_6
  - aws-c-cal=0.6.10=hb29e0c7_1
  - aws-c-common=0.9.13=hd590300_0
  - aws-c-compression=0.2.18=hecc5fa9_1
  - aws-c-event-stream=0.4.2=hf9b2f7b_4
  - aws-c-http=0.8.1=h5d7533a_5
  - aws-c-io=0.14.5=h50678d4_1
  - aws-c-mqtt=0.10.2=hf479d2b_4
  - aws-c-s3=0.5.2=h4ad9680_0
  - aws-c-sdkutils=0.1.15=hecc5fa9_1
  - aws-checksums=0.1.18=hecc5fa9_1
  - aws-crt-cpp=0.26.2=h19f5d62_7
  - aws-sdk-cpp=1.11.267=h5606698_1
  - bcrypt=4.1.2=py310hcb5633a_0
  - blinker=1.7.0=pyhd8ed1ab_0
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.1.0=py310hc6cd4ac_1
  - bzip2=1.0.8=hd590300_5
  - c-ares=1.27.0=hd590300_0
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - cffi=1.16.0=py310h2fee648_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - click=8.1.7=unix_pyh707e725_0
  - cloudpickle=2.2.1=pyhd8ed1ab_0
  - configparser=6.0.1=pyhd8ed1ab_0
  - contourpy=1.2.0=py310hd41b1e2_0
  - cryptography=42.0.5=py310h75e40e8_0
  - cycler=0.12.1=pyhd8ed1ab_0
  - databricks-cli=0.18.0=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - docker-py=6.1.3=pyhd8ed1ab_0
  - entrypoints=0.4=pyhd8ed1ab_0
  - expat=2.6.1=h59595ed_0
  - flask=3.0.2=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.49.0=py310h2372a71_0
  - freetype=2.12.1=h267a509_2
  - gettext=0.21.1=h27087fc_0
  - gflags=2.2.2=he1b5a44_1004
  - gitdb=4.0.11=pyhd8ed1ab_0
  - gitpython=3.1.42=pyhd8ed1ab_0
  - glib=2.78.4=hfc55251_0
  - glib-tools=2.78.4=hfc55251_0
  - glog=0.7.0=hed5481d_0
  - graphite2=1.3.13=h58526e2_1001
  - greenlet=3.0.3=py310hc6cd4ac_0
  - gst-plugins-base=1.22.9=h8e1006c_0
  - gstreamer=1.22.9=h98fc4e7_0
  - gunicorn=21.2.0=py310hff52083_1
  - harfbuzz=8.3.0=h3d44ed6_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - importlib-metadata=6.10.0=pyha770c72_0
  - importlib_resources=6.1.2=pyhd8ed1ab_0
  - itsdangerous=2.1.2=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py310hd41b1e2_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.1=cxx17_h59595ed_2
  - libarrow=14.0.2=h5001e6d_10_cpu
  - libarrow-acero=14.0.2=h59595ed_10_cpu
  - libarrow-dataset=14.0.2=h59595ed_10_cpu
  - libarrow-flight=14.0.2=hf334d8d_10_cpu
  - libarrow-flight-sql=14.0.2=h469e5c9_10_cpu
  - libarrow-gandiva=14.0.2=h3f306ff_10_cpu
  - libarrow-substrait=14.0.2=h469e5c9_10_cpu
  - libblas=3.9.0=21_linux64_openblas
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=21_linux64_openblas
  - libclang=15.0.7=default_hb11cfb5_4
  - libclang13=15.0.7=default_ha2b6cf4_4
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.5.0=hca28451_0
  - libdeflate=1.19=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.1=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgcrypt=1.10.3=hd590300_0
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=h783c2da_0
  - libgomp=13.2.0=h807b86a_5
  - libgoogle-cloud=2.21.0=h72bcb37_2
  - libgoogle-cloud-storage=2.21.0=hc7a4891_2
  - libgpg-error=1.48=h71f35ed_0
  - libgrpc=1.61.1=h42401df_1
  - libiconv=1.17=hd590300_2
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=21_linux64_openblas
  - libllvm15=15.0.7=hb3ce162_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnl=3.9.0=hd590300_0
  - libnsl=2.0.1=hd590300_0
  - libnuma=2.0.16=h0b41bf4_1
  - libogg=1.3.4=h7f98852_1
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libopus=1.3.1=h7f98852_1
  - libparquet=14.0.2=h352af49_10_cpu
  - libpng=1.6.43=h2797004_0
  - libpq=16.2=h33b98f1_0
  - libprotobuf=4.25.2=h08a7969_1
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.45.1=h2797004_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libsystemd0=255=h3516f8a_1
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.6.0=ha9c0a0a_2
  - libutf8proc=2.8.0=h166bdaf_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.6.0=hd429924_1
  - libxml2=2.12.5=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - lz4-c=1.9.4=hcb278e6_0
  - mako=1.3.2=pyhd8ed1ab_0
  - markdown=3.5.2=pyhd8ed1ab_0
  - markupsafe=2.1.5=py310h2372a71_0
  - matplotlib=3.8.3=py310hff52083_0
  - matplotlib-base=3.8.3=py310h62c0568_0
  - mlflow=2.8.1=py310ha13cd29_0
  - mpg123=1.32.4=h59595ed_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.4=h59595ed_2
  - nspr=4.35=h27087fc_0
  - nss=3.98=h1d7d5a4_0
  - numpy=1.26.4=py310hb13e2d6_0
  - oauthlib=3.2.2=pyhd8ed1ab_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.2.1=hd590300_0
  - orc=1.9.2=h00e871a_2
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.2.1=py310hcc13569_0
  - paramiko=3.4.0=pyhd8ed1ab_0
  - pcre2=10.42=hcad00b1_0
  - pillow=10.2.0=py310h01dd4db_0
  - pip=23.3.1=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - plotly=5.19.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - prometheus_client=0.20.0=pyhd8ed1ab_0
  - prometheus_flask_exporter=0.23.0=pyhd8ed1ab_0
  - protobuf=4.25.2=py310ha8c1f0e_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pulseaudio-client=16.1=hb77b528_5
  - pyarrow=14.0.2=py310hf9e7431_10_cpu
  - pycparser=2.21=pyhd8ed1ab_0
  - pyjwt=2.8.0=pyhd8ed1ab_1
  - pynacl=1.5.0=py310h2372a71_3
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.9=py310h04931ad_5
  - pyqt5-sip=12.12.2=py310hc6cd4ac_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.10.13=hd12c33a_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.10=4_cp310
  - pytz=2023.4=pyhd8ed1ab_0
  - pywin32-on-windows=0.1.0=pyh1179c8e_3
  - pyyaml=6.0.1=py310h2372a71_1
  - qt-main=5.15.8=h5810be5_19
  - querystring_parser=1.2.4=py_0
  - rdma-core=50.0=hd3aeb46_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - s2n=1.4.5=h06160fa_0
  - scikit-learn=1.4.1.post1=py310h1fdf081_0
  - scipy=1.12.0=py310hb13e2d6_2
  - setuptools=69.1.1=pyhd8ed1ab_0
  - sip=6.7.12=py310hc6cd4ac_0
  - six=1.16.0=pyh6c4a22f_0
  - smmap=5.0.0=pyhd8ed1ab_0
  - snappy=1.1.10=h9fff704_0
  - sqlalchemy=2.0.28=py310h2372a71_0
  - sqlparse=0.4.4=pyhd8ed1ab_0
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tenacity=8.2.3=pyhd8ed1ab_0
  - threadpoolctl=3.3.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - tornado=6.4=py310h2372a71_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - tzdata=2024a=h0c530f3_0
  - ucx=1.15.0=h75e419f_3
  - unicodedata2=15.1.0=py310h2372a71_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - websocket-client=1.7.0=pyhd8ed1ab_0
  - werkzeug=3.0.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.41=hd590300_0
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7f98852_2
  - zipp=3.17.0=pyhd8ed1ab_0
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - appdirs==1.4.4
      - docker-pycreds==0.4.0
      - psutil==5.9.8
      - sentry-sdk==1.40.6
      - setproctitle==1.3.3
      - wandb==0.16.4
prefix: /home/grabe/miniconda3/envs/mlflow-b71ce8844054e0c802e265ec9d1ee4558a5639cf
